# Types of 
cnames = ['ny','nx','lat','lon','area_m2','run','gpp',
                  'ra','npp','rc','et','gpp_sig','ra_sig','npp_sig',
                  'rc_sig','et_sig','cmass','cleaf','cfroot','cawood','g1_cwm','vcmax_cwm','tleaf_cwm',
                  'twood_cwm','troot_cwm','aleaf_cwm','awood_cwm','aroot_cwm',
                  'g1_cwv','vcmax_cwv','tleaf_cwv','twood_cwv','troot_cwv',
                  'aleaf_cwv','awood_cwv','aroot_cwv','g1_cwm0','vcmax_cwm0','tleaf_cwm0',
                  'twood_cwm0','troot_cwm0','aleaf_cwm0','awood_cwm0','aroot_cwm0',
                  'g1_cwv0','vcmax_cwv0','tleaf_cwv0','twood_cwv0','troot_cwv0',
                  'aleaf_cwv0','awood_cwv0','aroot_cwv0']

dtypes = {'ny' : 'i2',
          'nx' : 'i2',
          'lat': 'f4',
          'lon': 'f4',
          'forest': 'i2',
          'area_m2':'f4',
          'run': 'i2',
          'gpp': 'f4',
          'ra': 'f4',
          'npp':'f4',
          'rc':'f4',
          'et':'f4',
          'wue':'f4',
          'cue':'f4',
          'cmass':'f4',
          'cleaf':'f4',
          'cfroot':'f4',
          'cawood':'f4',
          'g1_cwm':'f4',
          'vcmax_cwm':'f4',
          'tleaf_cwm':'f4',
          'twood_cwm':'f4',
          'troot_cwm':'f4',
          'aleaf_cwm':'f4',
          'awood_cwm':'f4',
          'aroot_cwm':'f4',
          'g1_cwv':'f4',
          'vcmax_cwv':'f4',
          'tleaf_cwv':'f4',
          'twood_cwv':'f4',
          'troot_cwv':'f4',
          'aleaf_cwv':'f4',
          'awood_cwv':'f4',
          'aroot_cwv':'f4'}


dtypes_list = [('ny', 'i2'),
               ('nx', 'i2'),
               ('lat', 'f4'),
               ('lon', 'f4'),
               ('forest', 'i2'),
               ('area_m2', 'f4'),
               ('run', 'i4'),
               ('gpp', 'f4'),
               ('ra', 'f4'),
               ('npp', 'f4'),
               ('rc', 'f4'),
               ('et', 'f4'),
               ('wue', 'f4'),
               ('cue', 'f4'),
               ('cmass', 'f4'),
               ('cleaf', 'f4'),
               ('cfroot', 'f4'),
               ('cawood', 'f4'),
               ('g1_cwm', 'f4'),
               ('vcmax_cwm', 'f4'),
               ('tleaf_cwm', 'f4'),
               ('twood_cwm', 'f4'),
               ('troot_cwm', 'f4'),
               ('aleaf_cwm', 'f4'),
               ('awood_cwm', 'f4'),
               ('aroot_cwm', 'f4'),
               ('g1_cwv', 'f4'),
               ('vcmax_cwv', 'f4'),
               ('tleaf_cwv', 'f4'),
               ('twood_cwv', 'f4'),
               ('troot_cwv', 'f4'),
               ('aleaf_cwv', 'f4'),
               ('awood_cwv', 'f4'),
               ('aroot_cwv', 'f4')]
